# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rsc_d2subspace <- function(X, projection, center) {
    .Call('_Rsubclust_rsc_d2subspace', PACKAGE = 'Rsubclust', X, projection, center)
}

